### ISSUE TITLE
Failed to generate .d.ts.Error: Failed to generate .d.ts.

### ISSUE THREAD

**Issue by MattiSig** [piglovesyou/graphql-let#118] opened 2020-07-10 17:32 UTC
Something in the new reslease broke the generation of .d.ts.

I'm getting the error
```
yarn run v1.22.4
$ graphql-let
[ graphql-let ] Generating .d.ts...
[ graphql-let ] Failed to generate .d.ts.Error: Failed to generate .d.ts.
    at Object.genDts (C:\Users\USER_NAME\client\node_modules\graphql-let\dist\lib\dts.js:71:15)
    at processDtsForCodegenContext (C:\Users\USER_NAME\client\node_modules\graphql-let\dist\lib\full-generate.js:97:31)
    at Object.fullGenerate [as default] (C:\Users\USER_NAME\client\node_modules\graphql-let\dist\lib\full-generate.js:112:15)
    at async gen (C:\Users\USER_NAME\client\node_modules\graphql-let\dist\gen.js:26:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! with-typescript-graphql@0.1.0 dev: `yarn codegen && next`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the with-typescript-graphql@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\matthiass\AppData\Roaming\npm-cache\_logs\2020-07-10T16_41_33_559Z-debug.log
```

I just did a clean
```
yarn create next-app --example with-typescript-graphql with-typescript-graphql-app
yarn
yarn dev
```

Here is my package.json
```
{
  "name": "with-typescript-graphql",
  "version": "0.1.0",
  "author": "",
  "license": "ISC",
  "scripts": {
    "codegen": "graphql-let",
    "dev": "yarn codegen && next",
    "build": "yarn codegen && next build",
    "start": "next start"
  },
  "dependencies": {
    "@apollo/react-common": "3.1.4",
    "@apollo/react-components": "^3.1.5",
    "@apollo/react-hooks": "3.1.5",
    "apollo-cache": "^1.3.5",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link": "1.2.14",
    "apollo-link-http": "1.5.17",
    "apollo-link-schema": "1.2.5",
    "apollo-server-micro": "^2.14.2",
    "apollo-utilities": "^1.3.3",
    "graphql": "^14.6.0",
    "graphql-tag": "^2.10.3",
    "next": "latest",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^1.15.1",
    "@graphql-codegen/plugin-helpers": "^1.15.1",
    "@graphql-codegen/typescript": "^1.13.3",
    "@graphql-codegen/typescript-operations": "^1.13.3",
    "@graphql-codegen/typescript-react-apollo": "^1.13.3",
    "@graphql-codegen/typescript-resolvers": "^1.15.1",
    "@types/react": "^16.9.34",
    "@types/react-dom": "^16.9.7",
    "graphql-let": "0.x",
    "typescript": "^3.8.3"
  }
}

On a windows machine with npm@latest

Reverting to graphql-let: "0.10.0" fixed the issue
```

**Comment by marklawlor** [comment] 2020-07-11 13:17
Confirming that the issue isn't just the latest release, it occurs with both `v0.11.1` and `v0.11.0`

Downgrading back to `v0.10.0` works as expected

**Comment by piglovesyou** [comment] 2020-07-11 23:34
Apology for the regression. Please use v0.10.1 for now. I think I need days to start to work on the issue.

**Comment by piglovesyou** [comment] 2020-07-12 09:46
I happened to have time and released v0.11.2. Thanks for commenting. Please reopen it if you still get trouble.

**Comment by marklawlor** [comment] 2020-07-13 14:17
@piglovesyou After updating to v0.11.2 I get the error 

```
[ graphql-let ] Generating .d.ts...
[ graphql-let ] Cannot destructure property 'dtsFullPath' of 'codegenContext[i]' as it is undefined.TypeError: Cannot destructure property 'dtsFullPath' of 'codegenContext[i]' as it is undefined.
```

**Comment by piglovesyou** [comment] 2020-07-13 23:07
Thanks, it's so helpful to let me know the case. I'll continue to handle it here.

**Comment by piglovesyou** [comment] 2020-07-13 23:57
@marklawlor I'd like you to try v0.11.3 if you have time. Thank you.

**Comment by marklawlor** [comment] 2020-07-18 08:56
@piglovesyou Still getting a very similar error message in v0.12.0

```
[ graphql-let ] Local schema files are detected. Generating resolver types...
  ✔ Parse configuration
  ✔ Generate outputs
  ✔ Parse configuration
  ✔ Generate outputs
  ✔ Parse configuration
  ✔ Generate outputs
  ✔ Parse configuration
  ✔ Generate outputs
  ✔ Parse configuration
  ✔ Generate outputs
  ✔ Parse configuration
[ graphql-let ] Generating .d.ts...
[ graphql-let ] Cannot destructure property 'dtsFullPath' of 'codegenContext[i]' as it is undefined.TypeError: Cannot destructure property 'dtsFullPath' of 'codegenContext[i]' as it is undefined.
    at processDtsForCodegenContext (*****/node_modules/graphql-let/dist/lib/full-generate.js:118:17)
    at async Object.fullGenerate [as default] (*****/node_modules/graphql-let/dist/lib/full-generate.js:131:9)
    at async gen (*****/node_modules/graphql-let/dist/gen.js:27:34)
```

v0.10.1 is still working as expected

**Comment by piglovesyou** [comment] 2020-07-19 02:48
Thank you for reporting it again. Hmm, this is weird.

**Comment by marklawlor** [comment] 2020-07-26 10:54
From my very quick look, the issue is inside the function `processDtsForCodegenContext`

The variable `dtsContents` is an array of typescript files in my project as strings https://github.com/piglovesyou/graphql-let/blob/6724175682409d1cb34a38867a6747dc919ee95e/src/lib/full-generate.ts#L173

The function `processDtsForCodegenContext` expects that array's length to be smaller or  equal to the codegenContext https://github.com/piglovesyou/graphql-let/blob/6724175682409d1cb34a38867a6747dc919ee95e/src/lib/full-generate.ts#L179-L180

As I have significantly more Typescript files than files importing `*.graphql`, the variable `i` will go out of range.

**Comment by piglovesyou** [comment] 2020-07-27 00:24
Thank you very much for further check. We expect the number of `codegenContext` and `dtsContents` are always the same but something goes wrong. If possible, would you happen to have time to make a reproduction project?

**Comment by botond-veress** [comment] 2020-07-30 19:04
This issue happened to me yesterday when I had typescript files near the graphql schema. They were importing the graphql schema (not if this is important). After I put them in separate directories, the error went away. Weird.

**Comment by marklawlor** [comment] 2020-07-30 22:53
I forgot to mention that the issue will "go away" due graphql-let's caching of the files. During the first run, it will successfully create a cache of all the needed files before encountering the error. From this point onwards it seems to detect there is a file in the cache and perform different logic

You can replicate this by running

```
graphql-let # Errors
graphql-let # Run successfully
rm -rf node_modules/graphql-let/__generated__
graphql-let # Errors
```

While you can work around this for local development, it will break in most production deploys and/or CI environments.

**Comment by piglovesyou** [comment] 2020-07-31 01:21
Thank you guys for your helping. Hmm, what do I miss for the reproduction? We know:

* v0.10.0 was fine. The failure starts at v0.10.1. The error log has changed as I've worked on it, but still bad.
* Resolver Types is related
* It happens when catches aren't there
* I tried and [with-typescript-graphql example](https://github.com/vercel/next.js/tree/canary/examples/with-typescript-graphql#readme) with graphql-let@0.12.0 couldn't reproduce it even though I erase `node_modules/graphql-let/__generated__`

**Comment by marklawlor** [comment] 2020-07-31 01:49
I miss typed above, failure starts at v0.11.0

**Comment by marklawlor** [comment] 2020-07-31 03:12
I think I've narrowed down the issue a bit, but don't have a full reproduction just yet

- v0.11.0 is the version that breaks
- Using Resolver Types
- Use resolver type mapping and map a type to an exported class
- Possibly the "baseUrl" tsconfig setting is involved.

**Comment by marklawlor** [comment] 2020-07-31 09:28
Replicated issue using a slightly modified example here https://github.com/marklawlor/graphql-let-118

Points to note:

- Running graphql-let still generates the caches and .d.ts files, but exits with the error
- The command graphql-let will only error when there is no __generated__ folder
- Removing the baseUrl option from tsconfig will stop the error, but I would expect this library to work regardless of this option

**Comment by piglovesyou** [comment] 2020-07-31 13:02
You did it @marklawlor ...🤯  Your example is perfect 🎉

* `"baseUrl": "."` in tsconfig.yml
* `confog.mappers.Users: lib/user#User` for `@graphql-codegen/typescript-resolvers`

It's completely my fault, I didn't understand TypeScript API. Now I can fix it.

1. Generated `.tsx` imports `'"lib/user"` because of the config of GraphQL code generator
2. And tsconfig.json has `"baseUrl"`
3. Even though I pass only `.tsx`s to TypeScript API, it can generate additional `.d.ts`s since `.tsx` could import modules that are able to be resolved by `baseUrl`. The `.tsx`s are just entrypoints.

**Closed** 2020-08-02 01:54 UTC

**Comment by piglovesyou** [comment] 2020-08-02 01:57
@marklawlor Glad if you could try v0.12.1 :)

**Comment by marklawlor** [comment] 2020-08-02 03:05
@piglovesyou It works! Thanks for fixing such an weird edge case bug

**Comment by piglovesyou** [comment] 2020-08-02 04:34
It wasn't, I think you saved a lot of time that the future users will have on the related troubles.
